name: Build Xiaomi MiR3 OpenWrt

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          libglib2.0-dev libelf-dev qemu-utils

      - name: Update & Install Feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load Custom Configuration
        run: |
          [ -e .config ] && echo "Using existing .config" || make defconfig

      - name: Download Library
        run: |
          make download -j8

      - name: Compile Firmware
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: MiR3_OpenWrt_Firmware
          path: bin/targets/ramips/mt7620/*.bin
